### ISSUE TITLE
feat: Provide a link/excerpt/screenshot to a demo/example rendered outpout

### ISSUE THREAD

**Issue by ichtestemalwieder** [typedoc2md/typedoc-plugin-markdown#102]
Hello,

thanks for the plugin! 

This is just a suggestion/feature-request. It would be helpfull, if one can see at a glance, how the generated outpout and rendered output/theme/design looks like. This avoids having to install the plugin, if one is searching for an alternative theme for typedoc. Thanks!

**Comment by tgreyuk** [comment]
https://github.com/typedoc2md/typedoc-plugin-markdown-examples
