### ISSUE TITLE
Typedoc-plugin-markdown to RestructuredFile ?

### ISSUE THREAD

**Issue by yboujraf** [typedoc2md/typedoc-plugin-markdown#120]
Dear @tom-grey, @Vinnl , @cancerberoSgx , @tusharmath , @jrylan

Nice work.

I am using sphinx-docs and could be nice if same plugin wwill exist for .rst file.

Best Regards,
Youssef

**Comment by tgreyuk** [comment]
Just reviewing old tickets. Could potentially write something to output reStructuredText if there was interest for it. Will leave open for discussion.

**Comment by Vinnl** [comment]
Interestingly when I was tagged I had no idea what Sphinx even was, but nowadays we're using it too. Our current setup is to render the Markdown generated by typedoc-plugin-markdown using [MyST-Parser](https://github.com/executablebooks/myst-parser), which works fine, but obviously direct ReST output would be more reliable. So consider this an expression of mild interest :)

**Comment by yboujraf** [comment]
Yes, i am still interresting for this.

Best regards

**Comment by tgreyuk** [comment]
@yboujraf ok this could be an interesting project. i will probably need to pick your brains once I have investigated a bit further.

**Comment by yboujraf** [comment]
Dear

You are welcome
