### ISSUE TITLE
feat(docusaurus): disable globals page

### ISSUE THREAD

**Issue by felipecrs** [typedoc2md/typedoc-plugin-markdown#202]
I just realized that my docs would look much fancier if I didn't had the globals page at all:

With: 
![image](https://user-images.githubusercontent.com/29582865/110151307-16d1b600-7dbf-11eb-9e00-8469e8d8dd4d.png)

Without
![image](https://user-images.githubusercontent.com/29582865/110151323-19cca680-7dbf-11eb-9c20-903cd9d7aead.png)

So the sidebar itself is my Table of Contents (therefore I don't need the Globals page).

So an option to disable it would be welcome. :-)

**Comment by tgreyuk** [comment]
We could use a similar sidebar option here to your suggestion for #203 `omitTOC`. It will still generate the page but it won't do any harm.

**Comment by felipecrs** [comment]
Hm... we could still access the Globals page by typing in the URL though.

**Comment by tgreyuk** [comment]
You could  - but if thats an issue then it can be a global option.

**Comment by felipecrs** [comment]
It's not really an big issue... but if it was up to me I would prefer to prevent it :-).

**Comment by tgreyuk** [comment]
@felipecrs still pondering over this one. On the face of it the page serves no purpose, but it may contain inline symbols in some cases and also without it there is no entry point / slug to the api. Category linking will help if it gets implemented https://github.com/facebook/docusaurus/issues/2643 as the 'API' category can have it own page thus clean up the sidebar.
