### ISSUE TITLE
Docusaurus Sidebar Category Support

### ISSUE THREAD

**Issue by dustinlacewell** [typedoc2md/typedoc-plugin-markdown#213]
It would be great to have the @category grouping reflected in the generated sidebars.

**Comment by tgreyuk** [comment]
The sidebars themselves currently only nest one level deep so not too sure how this would work in practice. The categories should appear on the secondary TOC on the right?

**Comment by dustinlacewell** [comment]
Dunno, I'm just a dumb user. I guess it's a question of design. But the categories are there and it'd be nice to reflect them on the the front-end one way or another.

**Comment by gpbl** [comment]
I believe the idea is to output the reflections by categories first. 

For example,  in https://react-day-picker-next.netlify.app/api, in the sidebar there's "Functions", while I would like to have "Components" when the function is a component. 

Maybe @dustinlacewell was suggesting to use the `@category` tag?

**Comment by tgreyuk** [comment]
@category support for sidebar implemented in docusaurus-plugin-typedoc@next

**Comment by tgreyuk** [comment]
docusaurus-plugin-typedoc@1.0.0
typedoc-plugin-markdown@4.0.0

**Comment by gpbl** [comment]
Love it @tgreyuk , I could use categories in the sidebar: https://react-day-picker.js.org/next/api 🎉
