### ISSUE TITLE
Instructions for contributing

### ISSUE THREAD

**Issue by klzns** [typedoc2md/typedoc-plugin-markdown#240]
Hi! That's an awesome project, thanks for your work!

I would like to contribute to a feature but I don't know how to run the tests of the project. Do you mind adding some instructions on how to setup and run the tests?

Thanks in advance

**Comment by klzns** [comment]
Just giving more context on what errors I'm hitting

I ran `yarn` and then `yarn test` on root and I got a bunch of TS errors:

![image](https://user-images.githubusercontent.com/284515/124330023-752a5d80-db41-11eb-90e9-93e530fe95e2.png)

**Comment by tgreyuk** [comment]
Yeah sorry been meaning to get around to writing contributing page, just been refactoring a few things.
