### ISSUE TITLE
Markdown path is not match origin URL

### ISSUE THREAD

**Issue by cary-hu** [typedoc2md/typedoc-plugin-markdown#262]
We want to render a side bar toc, but I got the url from project declaration, it's not match rendered markdown path:
![image](https://user-images.githubusercontent.com/41052104/140489020-1518573a-0aa3-4b1b-a73b-67afa20a127a.png)
![image](https://user-images.githubusercontent.com/41052104/140489034-b131865e-5d00-4e3f-b34a-60db9be43e37.png)

How can I got the right URL in the project declaration?

**Comment by tgreyuk** [comment]
Not entirely sure what I am looking at here. (sorry) In what context are you trying to create a sidebar?

**Comment by cary-hu** [comment]
In our case, we will use typedoc-plugin-markdown to generate our product API doc to markdown,

and then, 

we will serve those markdown in our site, and for more  comfortable experience, we will generate Table of Content in Sidebar but not inline TOC.

seems like :

![image](https://user-images.githubusercontent.com/41052104/143795378-6d9af7c8-92d7-4b59-893f-251e75bacf36.png)

But I have no idea to get all the correctly path for each markdown. 

If not the case for this plugin, sorry for disturbing

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0

https://www.typedoc-plugin-markdown.org/docs/navigation
