### ISSUE TITLE
Modify folder structure

### ISSUE THREAD

**Issue by fgatti675** [typedoc2md/typedoc-plugin-markdown#306]
Hi,
First of all thank you for the great plugin!
I am having an issue with the folder structure that is generated in a Docusaurus project from a typescript project.
By default it is generating a folder structure based on `ReflectionKind`, and that is being taken by default by the sidebars configuration. We have quite a big project with hundreds of exports and this setup is not working for us.
We have annotated every export with `@category` and was expecting to generate a folder structure based on those, but no luck. Any idea of how this can be achieved? Thanks!
PS: I know I could generate the sidebars manually but we have a lot of exports and it would be easy to forget adding a new export to the docs

**Comment by tgreyuk** [comment]
Hi.. thanks this is an interesting idea. I have been thinking about the ability to set a module based folder structure, rather than symbol based hierarchy. Structuring by category in addition would be a nice feature.

**Comment by fgatti675** [comment]
For a little more context, you can check how the generated structure looks like for us now:
https://firecms.co/docs/api/modules
It is a React library and for us it would make sense to split utility functions from components for example.
In the best case we could just use the @category tags only and totally ignore the reflection kinds :)

**Comment by tgreyuk** [comment]
To control output files use:
https://www.typedoc-plugin-markdown.org/docs/options#output-options

To control sidebar use:
https://www.typedoc-plugin-markdown.org/docs/options#navigationmodel
