### ISSUE TITLE
Hierarchy based folder structure

### ISSUE THREAD

**Issue by georgimld** [typedoc2md/typedoc-plugin-markdown#307]
Hello, 

I am trying to use your plugin, but I also want a hierarchy based folder structure. I tried achieving this by using your plugin along with [typedoc-theme-hierarchy](https://www.npmjs.com/package/typedoc-theme-hierarchy) but it seems the plugins are not compatible, or at least they're not working for me when used together. 

Is it possible to achieve this, either by using your plugin together with another plugin or by integrating this feature in your plugin?

Thank you!

**Comment by tgreyuk** [comment]
Yeah that plugin won't work, but introducing some flexibility in folder structure is something that i'd like to introduce.

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0 now follows project module hierarchy.
