### ISSUE TITLE
[FR] Ability to add a subtitle

### ISSUE THREAD

**Issue by sneko** [typedoc2md/typedoc-plugin-markdown#310]
Hi,

In my case I have my `/README.md` with all setup information... and the technical documentation through `Typedoc` into `/docs/*`. The breadcrumb is great to navigate (through the technical documentation) but I'm not able to make a link to `/README.md` so they can come back to the main presentation.

I tried to specify as option:
```
  name: `${process.env.npm_package_name} _([show presentation](../README.md))_`,
```

But if the breadcrumb is enabled, since the `name` is also used as a link when we are on a page like `/docs/classes/abc.md` it will break the markdown due to nested links.

In the meantime I disabled the breadcrumb but I think it would be great to be able to allow a subtitle or something like that to point to the root project description.

Thank you,

**Comment by tgreyuk** [comment]
Hello. Thanks for this. I think what is really needed is the ability to easily customise the template, something I have been looking at.

**Comment by tgreyuk** [comment]
https://www.typedoc-plugin-markdown.org/docs/customizing-output
