### ISSUE TITLE
docusaurus-plugin-typedoc - Ability to do something in between Markdown conversion and final build

### ISSUE THREAD

**Issue by Zamiell** [typedoc2md/typedoc-plugin-markdown#317]
Hello, and thanks for the excellent plugin.

I don't like some of the things that the plugin is doing, such as naming the root page to "Readme". Specifically, I would prefer it to be named "Introduction".

"No problem", I thought to myself. So I opened up the "docs/api/index.md" file, and changed `sidebar_label: "Readme"` to `sidebar_label: "Introduction"`.

However, doing this has no effect - the final HTML website is already generated by Docusaurus, so none of the changes that I make to the Markdown files will matter. And if I run `npm run build` again, it will blow away my changes, because it recreates the Markdown files from scratch from the TypeScript code.

So, I would like this plugin to expose a way to do changes to the Markdown files *after* they are generated, but *before* Docusaurus proceeds to convert them into HTML.

Brainstorming:
Perhaps the plugin should have an additional option alongside `out`, `tsconfig`, `readme`, and so on. It could be called "afterMarkdownGeneration", or something along those lines. It would take a reference to a function, and then that function would be synchronously called after all of the Markdown files are generated.

**Comment by tgreyuk** [comment]
Thank you for this.

On the specific point about the readme sidebar label, although not documented can actually already be achieved by adding `sidebar.readmeLabel` to the plugin options ie:
```
 sidebar: {
          readmeLabel: 'Introduction',
        },
``` 
I take your point about further customisation to the output, TypeDoc already exposes events to achieve the same thing that can be used with custom plugins.  I have been also been working on refactoring the code and making it easier to customise and override the Docusaurus theme but not quite there yet.

**Comment by Zamiell** [comment]
Tom, thanks for the quick reply.

> On the specific point about the readme sidebar label, although not documented can actually already be achieved by adding sidebar.readmeLabel to the plugin options

Thanks. I'll try that. Can we document that please? I can submit a PR if you want.

> I take your point about further customisation to the output, TypeDoc already exposes events to achieve the same thing that can be used with custom plugins. I have been also been working on refactoring the code and making it easier to customise and override the Docusaurus theme but not quite there yet.

Aye, there are actually many modifications that I want to make to the output, not just the name of the readme. =(

Related: Docusaurus exposes an option called `sidebarItemsGenerator` that is useful here. (I wanted to customize the sidebar.) But frustratingly, if you specify a specific sidebar label in the `sidebarItemsGenerator` callback, it won't work, because this plugin also generates a sidebar label in the frontmatter, and the YAML frontmatter "wins".

So, I'm stuck and not sure how to proceed here, I think I might just need to fork the library. I'm also considering just using `typedoc-plugin-markdown` directly, and then writing a script to modify the Markdown files. Can you give a list of all the things that `docusaurus-plugin-typedoc` actually does? I see that it is:

1) generating frontmatter (which affects the sidebar)
2) arbitrarily removing the first line, which is the "path" to the Markdown file
3) fixing the title to be more plain
4) arbitrarily removing the table of contents (which presumably isn't needed with Docusaurus because its on the right hand side)

Besides this, I'm curious if there's any magic going on that it is doing?

**Comment by tgreyuk** [comment]
> Related: Docusaurus exposes an option called sidebarItemsGenerator that is useful here. (I wanted to customize the sidebar.) But frustratingly, if you specify a specific sidebar label in the sidebarItemsGenerator callback, it won't work, because this plugin also generates a sidebar label in the frontmatter, and the YAML frontmatter "wins".

So another thing you can do ( sorry undocumented again :( ) is to pass `sidebar.autoConfiguration=false` to the options. This will omit all sidebar related yaml items and also the category.yml files.

```
 sidebar: {
          autoConfiguration: false,
        },
```

I will update the readme.

> Besides this, I'm curious if there's any other magic that it is doing?

Not really - it is a pretty simple wrapper, the main thing as you say is adding yaml to the pages and setting up default options for docusaurus (removing breadcrumbs, page title etc). As I say the aim is to do make it very easy to customise the theme in the same way as the html theme works.

**Comment by Zamiell** [comment]
As a small update on this, I ended up deciding to use `typedoc-plugin-markdown` directly, and then writing a script to modify the Markdown files in an arbitrary way.

In case anyone wants to do something similar, here is my horrible, terrible code: https://github.com/IsaacScript/isaacscript/blob/main/packages/docs/scripts/fixIsaacScriptCommon.ts

Some day, it would be fantastic for the plugin to support some of this stuff directly via configuration options.

**Comment by tgreyuk** [comment]
https://www.typedoc-plugin-markdown.org/docs/customizing-output

**Comment by pettyron** [comment]
I know this issue is closed and somewhat old. I'm leaving this comment for anyone that finds themselves in this same situation and lands on this issue. Because I too found it frustrating that I could not control the front-matter precisely. In my case, it was a changelog that I wanted to pass on and customize.

You don't need some script to work around this. You just need to spoof the parser with a double block of front-matter. The plugin already uses a description block internally. Then strips it out of the parsed markdown to Docusaurus. Knowing that you can do something like this:

```markdown
---
description: The description that the plugin will use internally.
---

---

title: changelog
sidebar_label: changelog
slug: /changelog

---

# My Module's CHANGELOG

Initial Release:
...
```
Then the output file in Docusaurus should look like this:
```markdown
---

title: changelog
sidebar_label: changelog
slug: /changelog

---

# My Module's CHANGELOG

Initial Release:
...
```
It's important to note that the spacing in the second block is important. Otherwise, editors like VS Code might try to convert to headings etc. Just because it thinks you're trying to title something with horizontal rules etc. Granted this is brittle and might be patched in the future. But right now this behavior is a thing. Personally, I believe there should just be a setting that allows front-matter to be explicitly forwarded out of markdown files. It would be nice just to be able to forward the front-matter you want on to the parsed files.

Unfortunately, this only works on markdown files. Manipulating front-matter within a JSDoc comment would be nice as well. But I understand the complexity behind something like that.
