### ISSUE TITLE
Including plugin multiple times breaks sidebar

### ISSUE THREAD

**Issue by strawberry-choco** [typedoc2md/typedoc-plugin-markdown#352]
I use the `vuepress-plugin-typedoc` plugin to generate the needed files for vuepress. The thing is I have a mono repo with packages inside them, which are independent of each other and I don't want their types to be mixed together. So I included the plugin multiple times in the vuepress config and it generates the config just fine, except for one thing: the sidebar, which is only generated properly in one of the packages but not the other.

Accessing the subpages like e.g. `http://localhost:8080/api/package1/classes/Class1.html` still works fine.

Config:
```ts
export default defineUserConfig({
  title: 'bug reproduce repo',
  bundler: webpackBundler({
    postcss: {},
    vue: {},
  }),
  plugins: [
    typedocPlugin({
      entryPoints: ['packages/package1/src/index.ts'],
      tsconfig: 'packages/package1/tsconfig.json',
      out: 'api/package1',
    }),
    typedocPlugin({
      entryPoints: ['packages/package2/src/index.ts'],
      tsconfig: 'packages/package2/tsconfig.json',
      out: 'api/package2',
    }),
  ]
});
```

How to reproduce:
- Clone `https://github.com/strawberry-choco/typedoc-monorepo-sidebar`
- Run `yarn install`
- Run `yarn run docs:serve`

![firefox_9EYlJRg3mR](https://user-images.githubusercontent.com/20382692/190621236-1321a541-5955-4489-9a18-35d8044db406.png)

![firefox_k49clb8umb](https://user-images.githubusercontent.com/20382692/190621262-d66dbdf5-f065-4b97-aef1-22b272e3707f.png)

**Comment by tgreyuk** [comment]
FYI moving away from the VuePress plugins in favour of a simple Vitepress theme that works outside of plugin ecosystem. Can be used with VuePress. https://github.com/tgreyuk/typedoc-plugin-markdown/tree/next/packages/typedoc-vitepress-theme#readme .

**Comment by tgreyuk** [comment]
The vuepress plugin has been officially deprecated. Please use typedoc-vitepress-theme (https://typedoc-plugin-markdown.org/plugins/vitepress) which is VuePress compatible.
