### ISSUE TITLE
Whether typedoc can generate Markdown files according to the directory structure

### ISSUE THREAD

**Issue by He110te4m** [typedoc2md/typedoc-plugin-markdown#353]
I'm writing Vue 3's Component Library, which has some hooks (the TS function) . The comments within the component are parsed by the AST and extracted into a Markdown file that is rendered by VitePress, which is generated according to the directory structure. However, when Typedoc is generated, it prints everything to a file. This is very difficult to process and display in a component library.

Whether `typedoc` can generate `Markdown` files according to the directory structure?

**Comment by tgreyuk** [comment]
Version 4 has some additional output options which should hopefully fit most usecases. https://www.typedoc-plugin-markdown.org/docs/options#output-options .
