### ISSUE TITLE
The readmeFile param monorepo config is not considered when the .md file is generated

### ISSUE THREAD

**Issue by maz-e** [typedoc2md/typedoc-plugin-markdown#383]
As it says in https://typedoc.org/guides/monorepo/#typedoc-package-config, the README file set in the `readmeFile` config should be displayed on the index page of the package doc. Still, when the plugin generates the package/module .md file, only the classes, types or interfaces are displayed, and the README file is removed from the content.

**Comment by tgreyuk** [comment]
This had been fixed, but only in the next version. (typedoc-plugin-markdown@next).

Some docs here: https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/typedoc-plugin-markdown/docs/readme-files.md

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0
