### ISSUE TITLE
Potential bug with optional function argument

### ISSUE THREAD

**Issue by Zamiell** [typedoc2md/typedoc-plugin-markdown#396]
Hello,
I think I found a bug in the plugin.

Here's the source code for a function called "spawnCustomGridEntity":
<https://github.com/IsaacScript/isaacscript/blob/4d4cfd0/packages/isaacscript-common/src/classes/features/callbackLogic/CustomGridEntities.ts#L229-L237>

We can see that it has, in order:
- 2 mandatory arguments
- 3 optional arguments
- 2 more optional arguments, with a default value specified

TypeDoc makes the output of the function look like this:
<https://isaacscript.github.io/isaacscript-common/features/CustomGridEntities#parameters>

We can see that the final two arguments do not have the question mark like the other optional arguments do, which seems to be a bug.

**Comment by tgreyuk** [comment]
Interesting - we can easily flag default params as optional (which technically they are), but what if the first argument has a default value.? In this case you would have to pass in null or undefined to the first argument.

**Comment by Zamiell** [comment]
That's true. So perhaps the plugin should only mark arguments as being "optional" if they are not followed by a non-optional argument.

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0
