### ISSUE TITLE
How to export interface as a table

### ISSUE THREAD

**Issue by ccnwjsqdfky55** [typedoc2md/typedoc-plugin-markdown#403]
I find the table form is more beautiful, can I output the definition of interface as a table form now?

**Comment by tgreyuk** [comment]
Not yet - but will add an option for that in next release.

**Comment by tgreyuk** [comment]
This is a now available as an experimental option is in the `next` pre-release:

```
--propertiesFormat
Specify the render style of properties groups for Interfaces and Classes. Expected values [List, Table].
```

`npm install typedoc-plugin-markdown@next`

`--propertiesFormat Table`

Feel free to try it out.

**Comment by ccnwjsqdfky55** [comment]
My Version Information 
 "typedoc": "^0.23.24",
  "typedoc-plugin-markdown": "4.0.0-next.7",

I get the following error

TypeDoc exiting with unexpected error:
TypeError: typedoc_1.ReflectionKind.singularString is not a function

**Comment by ccnwjsqdfky55** [comment]
I use 4.0.0-next.6 and I don't have this problem

**Comment by fabrizio-vitale-deltatre** [comment]
Piggybacking on this question, I've got the opposite problem:

I'd like to render types with an interface-like format.

My issue is that headings, lists  and code blocks do not get rendered correctly when are defined in tsdoc coments of properties:

```ts
import type { A, B, C, } from './other'

type MyType = {
  /**
  * ```ts
  * // I'm a codeblock example
  * const t: MyType = { type: 2 } 
  * ```
  *
  */
  type: A | B | C
}
```

---

I've quickly skimmed [next](https://github.com/tgreyuk/typedoc-plugin-markdown/tree/next) and it seems that there's an option `typeDeclarationFormat` that could be useful.

It doesn't seem implemented tho:

<img width="1033" alt="Screenshot 2023-05-08 at 16 14 51" src="https://user-images.githubusercontent.com/117928938/236850717-4de4eb09-46be-473f-b177-3659d467ba47.png">

---

Do you have an example on how to use these format options?

**Comment by tgreyuk** [comment]
@fabrizio-vitale-deltatre apologies - the option `typeDeclarationFormat` is available again in docusaurus-plugin-typedoc@1.0.0-next.9

**Comment by CoderIllusionist** [comment]
Can we use `--propertiesFormat` with `docusaurus-plugin-typedoc` ?

**Comment by CoderIllusionist** [comment]
@tgreyuk Thanks, that did it for me

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0

https://typedoc-plugin-markdown.org/docs/options#propertiesformat
