### ISSUE TITLE
Recommended way to match format and styles

### ISSUE THREAD

**Issue by jeffchuber** [typedoc2md/typedoc-plugin-markdown#428]
hi there,

i want to use this project to match the documentation formatting and styling coming out of pydoc-markdown. 

what is the recommended way to adjusting the formatting and styling of the output? 

i looked inside the project and it appears it would take significant surgery to go beyond the flags but perhaps i am missing something.

i appreciate any pointers or suggestions!

**Comment by tgreyuk** [comment]
Do you want to pipe some generated markdown through `pydoc-markdown` or just create some documentation that matches its output? If its the latter you are probably better off just trying to customise the html theme.

**Comment by jeffchuber** [comment]
Ideally the latter. 

I did look into that, but I quickly grew afraid =D - any examples of people who have done this? (again I understand if this is not a current priority)

**Comment by tgreyuk** [comment]
As previously mentioned to match specific UIs with themes would require to a new HTML theme as Markdown is too restrictive.
