### ISSUE TITLE
Error from plugin does not crash Docusaurus build

### ISSUE THREAD

**Issue by PatrikTrefil** [typedoc2md/typedoc-plugin-markdown#429]
## Observed behavior

If the generation of the markdown files throws errors, then the whole build is considered to be successful.

## Expected behavior

The build should fail.

## Steps to reproduce

1. Setup the plugin with docusaurus
2. Do not install dependencies in the TypeScript project
3. `docusaurus build`

Should get something like this:

```
../src/web-app/pages/prehled.tsx:7:18 - error TS2307: Cannot find module 'next/head' or its corresponding type declarations.

7 import Head from "next/head";
```

The `docusaurus build` returns status code 0.

**Comment by tgreyuk** [comment]
Thanks - good point - is fixed in next version.

**Comment by tgreyuk** [comment]
docusaurus-plugin-typedoc@1.0.0
