### ISSUE TITLE
`@group` is not respected when placed over a `type` and `allReflectionsHaveOwnDocument` is `false`

### ISSUE THREAD

**Issue by HarelM** [typedoc2md/typedoc-plugin-markdown#448]
I'm migrating MapLibre project documentation site to use TSDoc comments + TypeDoc + this plugin + mkdocs.
When I generate the site with out using this plugin I get the following results:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3269297/d3507d98-2758-40ff-8ef8-1fd873bb88c6)
This is how the site looks - note the Event Related group I created
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3269297/077474ec-7a7c-41db-aafe-27abe9f06e33)
After using this plugin I get the following (missing types, variables, etc):
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3269297/dbc4d6cb-efa7-40ae-8522-72fb54c98519)
And the Event Related is moved down and gets badly formmated:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3269297/51cc90f3-c386-4847-aac5-229bddc37c87)

The data can be found in the following repo - this is the commit I'm currently on:
https://github.com/maplibre/maplibre-gl-js/tree/0f5934a0f63db2674eae9121059fbf2da2a64f57 

I'm not sure what causes this, probably some bad comments structure...

**Comment by birkskyum** [comment]
I only see these - am I missing some code changes wrt classes/enums/interfaces?


<img width="219" alt="Screenshot 2023-07-06 at 10 49 05" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/74932975/f60fab52-d19b-48e0-8c28-3ee56bb61cdb">

**Comment by birkskyum** [comment]
I can see that all the data that as .html was in "types" now is inside of the modules/maplibregl.md

**Comment by HarelM** [comment]
I'm not sure, but this was from day 1, so it might be the way this plugin works, IDK...

**Comment by birkskyum** [comment]
@HarelM , I've found something. When I change "Event Related" to "EventRelated" both in the typedoc.json and in the files next to the `@group EventRelated` they appear in the intro

**Comment by birkskyum** [comment]
That is great! It appears the now-simplified module page has the potential to replace the intro.
http://0.0.0.0:8000/maplibre-docs-test/API/modules/maplibregl/

**Comment by birkskyum** [comment]
Maybe the title of this issue should be renamed to indicate types are not included in the @group when  allReflectionsHaveOwnDocument = false, to narrow it down;

**Comment by HarelM** [comment]
True, but this is the default... I'll see if I can fix the title.

**Comment by tgreyuk** [comment]
@HarelM Thanks for raising the issue. My main effort at the moment is to concentrate on the next version of this plugin which actually does address this issue -  `typedoc-plugin-markdown@next`. I'd be very happy to incorporate anything into this version. Updated options can be found in the readme https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/typedoc-plugin-markdown/README.md .

**Comment by HarelM** [comment]
Thanks for the info!
I'll wait patiently for it to be released :-)
I'm also looking for the removal of the kind prefix which I see you have added, so I'll wait for this version to come out.
Feel free to test the plugin with my repo, it has all sorts of edge cases I guess...

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0

**Comment by HarelM** [comment]
Thanks for the update! I'll take the new version for a ride and see how it behaves.
Thanks for all the time invested in this!
