### ISSUE TITLE
How to improve the formatting for types?

### ISSUE THREAD

**Issue by ziad-saab** [typedoc2md/typedoc-plugin-markdown#456]
The output of `typedoc-plugin-markdown` can sometimes be very difficult to read, especially when compared to its HTML counterpart. Here's an example of HTML and Markdown outputs from the same codebase:

HTML: https://metamask.github.io/keyring-api/latest/variables/KeyringAccountStruct.html
Markdown: https://docs.metamask.io/zs/keyring-doc/snaps/reference/keyring-api/modules/#keyringaccountstruct

The main difference being that the HTML output has one entry per line, whereas the Markdown output reads all on the same line, making it almost useless.

Thank you!

**Comment by tgreyuk** [comment]
Hi,

Markdown will ignore a single line break and trying to create a double line break won't work either. What I have been looking at is an option to wrap this kind of thing in a code block which will produce this kind of output:

<img width="870" alt="Screenshot 2023-08-01 at 22 59 39" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/8b2c5f67-3589-4962-90a1-9a7ba2077538">

**Comment by ziad-saab** [comment]
yes that would be perfect! if you can point me to a place in the code i can take a stab at it!

**Comment by tgreyuk** [comment]
> yes that would be perfect! if you can point me to a place in the code i can take a stab at it!

So this option is already available in next version so might not be worth the effort .

Options name is  `identifiersAsCodeBlocks`

https://github.com/tgreyuk/typedoc-plugin-markdown/tree/next/packages/typedoc-plugin-markdown

**Comment by ziad-saab** [comment]
@tgreyuk the new version with `identifiersAsCodeBlocks` looks much better! Here's an example:

<img width="1092" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3943143/d2679f0d-4018-4dca-b5c9-8c7b93b70b16">

Do you reckon anything can be done about the "Return Type" part?

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0

https://www.typedoc-plugin-markdown.org/docs/options#usecodeblocks
