### ISSUE TITLE
[docusaurus-plugin-typedoc]: add the ability to add a separate frontmatter for readme file.

### ISSUE THREAD

**Issue by aamir1995** [typedoc2md/typedoc-plugin-markdown#469]
Readme is an essential part of the documentation, sometimes it serves as the main page for docs, I want to add a separate frontmatter for a readme file, such as hiding the title, toc, and navigation, currently there's no way to do this only for the readme file, the `frontmatter` property applies to all the generated files.

It would be great if we had a way of specifying a separate set of standard frontmatter only for the readme.
It could look something like this
```
readmeFrontmatter: {
 // standard docusasrus frontmatter here
}
```

Thanks!

**Comment by tgreyuk** [comment]
https://typedoc-plugin-markdown.org/plugins/frontmatter/options#readmefrontmatter
