### ISSUE TITLE
Using the pluging always result in 1 module page with undefined links

### ISSUE THREAD

**Issue by mtirionMSFT** [typedoc2md/typedoc-plugin-markdown#474]
This is a Newby question for this plugin I'm afraid.

typedoc normally generates a hierarchy of the APi. Adding this plugin with or without --allReflectionsHaveOwnDocument results in a modules.md (just that one) with all links as undefined. Piece of the generated code:

```markdown
## Table of contents

### Classes

- [Calendar](undefined)

### Interfaces

- [AbsolutePosition](undefined)
- [AbsolutePositionOutput](undefined)
```

typedoc has seperate files for classes, functions, interfaces and types. How can I get that and fix the link issue?

**Comment by tgreyuk** [comment]
> typedoc has seperate files for classes, functions, interfaces and types. How can I get that and fix the link issue?

If recommend using the 'next' version that exports all members to own file (as per html theme) as default:

https://github.com/tgreyuk/typedoc-plugin-markdown/tree/next/packages/typedoc-plugin-markdown#readme

**Comment by mtirionMSFT** [comment]
@tgreyuk aha, that's useful. However, just tried it - @next version doesn't output anything now except for a .nojekyll file. Any way to see what's going wrong? I have tested I'm using the correct version.

**Comment by tgreyuk** [comment]
@mtirionMSFT ok that is not correct -  i don't suppose you'd be able to share your code/repo? I would be interested to know what is causing your issue and fix it?

**Comment by mtirionMSFT** [comment]
@tgreyuk no, can't share that I'm afraid. Let me see if I can "minify" the problem.
