### ISSUE TITLE
Support for categories (docusaurus plugin)

### ISSUE THREAD

**Issue by FC5570** [typedoc2md/typedoc-plugin-markdown#499]
I have the `@category` tag to group certain interfaces/classes under categories. This works normally using standalone typedoc (I have `navigation.includeCategories` set to true in both configs) but not using this plugin, docs generated have classes and interface sections only.

My config:

```
  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: ['../path-to-folder/index.ts'],
        tsconfig: '../path-to-folder/tsconfig.json',
        out: 'documentation',
        excludeExternals: true,
        navigation: {
            includeCategories: true
        },
      },
    ],
  ]
```

**Comment by tgreyuk** [comment]
thanks. This will be available in `next` version.

**Comment by tgreyuk** [comment]
categories and groups are now supported:

docusaurus-plugin-typedoc@1.0.0
typedoc-plugin-markdown@4.0.0
