### ISSUE TITLE
TSC cannot find vuepress-plugin-typedoc/next although it is present in node_modules

### ISSUE THREAD

**Issue by joonashak** [typedoc2md/typedoc-plugin-markdown#500]
TSC complains `Cannot find module 'vuepress-plugin-typedoc/next' or its corresponding type declarations. ts(2307)` when importing `vuepress-plugin-typedoc` in `config.ts` to configure vuepress. However, the dev server works as expected and build passes. Markdown generated by the plugin appears to be correct.

The project is set up according to vuepress docs and there is nothing extra. `vuepress-plugin-typedoc` is installed with NPM and present in `node_modules` where I can also see the `./next` export in `package.json`. I also tested with `vuepress-plugin-copy-code2` and importing that in `config.ts` works fine.

I tried creating `tsconfig.json` and fiddled with some basic options but nothing seemed to work. Is it necessary to have a specific `tsconfig.json` (or other) when using this plugin? Any other ideas what might be causing this behavior?

Thanks!

EDIT: Versions in question:

- `"typedoc": "^0.25.3"`
- `"typedoc-plugin-markdown": "^3.17.1"`
- `"vuepress": "^2.0.0-beta.68"`
- `"vuepress-plugin-typedoc": "^0.13.0"`

**Comment by tgreyuk** [comment]
The vuepress plugin has been deprecated. Please use `typedoc-vitepress-theme` (https://typedoc-plugin-markdown.org/plugins/vitepress) which is VuePress compatible.
