### ISSUE TITLE
Characters `<` and `>` are not being escaped using Docusarus 3.

### ISSUE THREAD

**Issue by aamir1995** [typedoc2md/typedoc-plugin-markdown#502]
The following generated markdown will result in an error while using the plugin with Docusarus 3 and MDX 3.
```
> **new View**<`CameraControllerTypes`, `CameraControllerKind`>(
```
<img width="1030" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/10736453/f5e9bfed-9510-40aa-a535-5951349e0224">

Probably need to escape these,

The issue can be reproduced by pasting the above problematic markdown in [MDX Playground](https://mdxjs.com/playground/)

This is also mentioned in upgrade guide of Docusarus V3 https://docusaurus.io/docs/migration/v3#common-mdx-problems

Environment Info:
Docusarus version: `3.0.0`
@mdx-js/react: `3.0.0`
docusaurus-plugin-typedoc: `1.0.0-next.21`
typedoc-plugin-frontmatter: `0.0.2`
typedoc-plugin-markdown: `4.0.0-next.27`

**Comment by tgreyuk** [comment]
Both opening and closing brackets should be escaped. Would you mind pasting in your source?

This looks like documentation of a class constructor but you should see this

```
> **new View**\<`CameraControllerTypes`, `CameraControllerKind`\>()
```

**Comment by CoderIllusionist** [comment]
@aamir1995 Tthis plugin generates plain markdown files, docusaurus treats these (by default in V3) as mdx (which is not vanilla md) files. I had the exact same error you had, i fixed it by adding 
```
  markdown: {
    format: 'detect'
  },
``` to `docusaurus.config.ts`

**Comment by DominicGBauer** [comment]
@CoderIllusionist thanks for the suggestion! I was having issues with using { } in a JS comment throwing an acorn error and using your suggestion fixed it.

**Comment by maerzhase** [comment]
@CoderIllusionist thanks man! this setting made my day :-)
