### ISSUE TITLE
class static functions are no longer marked as such since typedoc 0.25.3

### ISSUE THREAD

**Issue by panva** [typedoc2md/typedoc-plugin-markdown#533]
I have a reproduction for missing `Static` labels on static class methods since typedoc@0.25.3. 

I am opening an issue here because it is only exhibited in docs produced with the `typedoc-plugin-markdown` plugin, not when using the default html output without a plugin.

[Reproduction](https://github.com/panva/typedoc-repro) follows

```
gh repo clone panva/typedoc-repro
cd typedoc-repro
npm clean-install
npm run docs
node check.mjs

# In html Foo.bar is marked as Static true
# In md Foo.bar is marked as Static true

npm i -D typedoc@0.25.4
npm run docs
node check.mjs

# In html Foo.bar is marked as Static true
# In md Foo.bar is marked as Static false
```

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0
