### ISSUE TITLE
Duplication in callback/callable/function properties.

### ISSUE THREAD

**Issue by Shakeskeyboarde** [typedoc2md/typedoc-plugin-markdown#581]
Properties that have a function type, include a "Type Declaration" section that I would like to omit. Even though it's a function value, it's first and foremost a property, and I want it to appear the same as other non-function valued properties.

I've attached a screenshot illustrating what I mean. The `dir` property has no duplication. The `getDependencyLinks` property shows the function signature and description twice, as well as "Parameters" and "Returns" subsections which I think are unnecessary. If I wanted to have detailed documentation about the function type, I would declare it as a type alias, instead of having it inlined.

<img width="757" alt="Screenshot 2024-02-24 at 6 47 01 PM" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/781874/73a5d6ab-519d-4ba3-bd41-cb542eb9dafb">

**Comment by tgreyuk** [comment]
Thank you. This has actually already been fixed in typedoc-plugin-markdown@next .  Will leave this issue open though until v4 is released (not sure the fix will make it into v3).

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@4.0.0
