### ISSUE TITLE
--entryDocument Argument Is Ignored By typedoc-github-wiki-theme

### ISSUE THREAD

**Issue by DauntlessStudio** [typedoc2md/typedoc-plugin-markdown#590]
When using `--plugin typedoc-plugin-markdown --entryDocument MyDoc.md` the default file entry document, README.md, is overridden with MyDoc.md. 
However if `--plugin typedoc-plugin-markdown --plugin typedoc-github-wiki-theme --entryDocument MyDoc.md` is used then the entry document is still Home.md regardless of the provided argument.

**Comment by tgreyuk** [comment]
Thanks will take a look.

**Comment by tgreyuk** [comment]
Fix in:
typedoc-plugin-markdown@4.0.0
typeodoc-github-wiki-theme@2.0.0

please note the options has changed name to `entryFileName`.
