### ISSUE TITLE
Param object trans head not ok

### ISSUE THREAD

**Issue by jiawei397** [typedoc2md/typedoc-plugin-markdown#626]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

This is the `test.ts` code: 
```
/**
 * The application constructor.
 * @param param - The initial parameters.
 * @param param.container - The dom element to render scene.
 * @param param.background? - The background.
 */
class App {
  constructor(param: {
    container: HTMLElement;
    background?: number | string | Number[];
  }) {}
}
```

Now the param not ok:
```md
# Class: App

The application constructor.

## Param

The initial parameters.

## Param

The dom element to render scene.

## Param

The background.
```

But trans to html is ok:
<img width="395" alt="image" src="https://github.com/typedoc2md/typedoc-plugin-markdown/assets/19886374/8e94aa0b-da68-49ab-b580-277dc4024760">

### TypeDoc configuration

```
{
    "$schema": "https://typedoc.org/schema.json",
    "plugin": ["typedoc-plugin-markdown"],
    "entryPoints": ["./*.ts"],
    "out": "./docs"
}
```

### Expected behavior

```md
# Class: App

The application constructor.

## Param: param

The initial parameters.

## Param: param.container

The dom element to render scene.

## Param: param.background

The background.
```

**Comment by tgreyuk** [comment]
The comments need to be on the constructor (not the class):

<img width="607" alt="Screenshot 2024-05-28 at 18 37 51" src="https://github.com/typedoc2md/typedoc-plugin-markdown/assets/11680870/f59e7c19-ac9a-4152-b5ab-e14f55a23830">

**Comment by jiawei397** [comment]
> The comments need to be on the constructor (not the class):
> 
> <img alt="Screenshot 2024-05-28 at 18 37 51" width="607" src="https://private-user-images.githubusercontent.com/11680870/334515738-f59e7c19-ac9a-4152-b5ab-e14f55a23830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDYxMjAsIm5iZiI6MTcxNjk0NTgyMCwicGF0aCI6Ii8xMTY4MDg3MC8zMzQ1MTU3MzgtZjU5ZTdjMTktYWM5YS00MTUyLWI1YWItZTE0ZjU1YTIzODMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxMjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNTExNjg4ZGY4MjhiNWUyYjllOGIwNjJmNzdlZThiNjYyMWNkZjViNDZkZjE5YjYwYjg5NDYxOWI2MGRmNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MkZlrWh7Wjsb5-XZvh6yOvfh0KLdCdHV3Tbii-373I">

Got it. Thanks.
