### ISSUE TITLE
is it possible to reorder generated sections? 

### ISSUE THREAD

**Issue by ramitheeb** [typedoc2md/typedoc-plugin-markdown#627]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

is it possible to reorder the generated sections? i want the examples to show up above parameters

**Comment by tgreyuk** [comment]
So the ordering currently follows the behaviour of the default theme whereby block tags are intentionally rendered below the signature, but we could introduce an option to re-order how block tags are rendered. Would need to have a bit of a think on how this would be configured.

**Comment by tgreyuk** [comment]
You can now do:
```
{
  "blockTagsPreserveOrder": ["@example"]
}
```
Available in typedoc-plugin-markdown@4.2.0
