### ISSUE TITLE
Broken links in some local wiki reference

### ISSUE THREAD

**Issue by TL-Luca-Ricci** [typedoc2md/typedoc-plugin-markdown#628]
### What package is the bug related to?

typedoc-gitlab-wiki-theme

### Describe the issue

Some references to other wiki pages (usually to interfaces and enums, never see bad classes references) aren't stripped from `.md` extensions making the wiki point to the source page (raw content) instead of the actual page (with interpreted markdown)

### TypeDoc configuration

```json
{
    "$schema": "https://typedoc.org/schema.json",
    "entryPoints": ["./src/api.ts"],
    "plugin": ["typedoc-plugin-markdown", "typedoc-gitlab-wiki-theme"],
    "readme": "none",
    "enumMembersFormat": "table",
    "expandObjects": true,
    "parametersFormat": "table",
    "expandParameters": true,
    "propertiesFormat": "table",
    "typeDeclarationFormat": "table",
    "indexFormat": "table",
    "flattenOutputFiles": false,
    "out": "wiki"
}
```

### Expected behavior

All the links should have the `.md` extension removed

**Comment by tgreyuk** [comment]
Should be fixed in typedoc-gitlab-wiki-theme@.2.0.1
