### ISSUE TITLE
Parse functions into a table or a list

### ISSUE THREAD

**Issue by amkuchta** [typedoc2md/typedoc-plugin-markdown#638]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

Currently, lists of functions parse solely into a list format;

#### Example
```ts
/**
 * @function fromJson - The method used to parse a class from a valid JSON string
 * @function toJson - The method used to parse a class to a valid JSON string
 * @function toObject - The method used to parse a class to a generic TypeScript {@linkcode Object}
 * @function validate - The method used to parse a class to a generic TypeScript {@linkcode Object}
 * @function clone - The method used to clone a class to an identical copy of itself
*/
```
![image](https://github.com/typedoc2md/typedoc-plugin-markdown/assets/6255186/0cd41a10-1573-44c0-b16b-ca2cdc72eb21)

### Proposed solution

Functions should be able to be parsed into a list similar to how properties are for stylistic consistency

**Comment by amkuchta** [comment]
It may be worthwhile to extend this to `returns` values, as well - while only one item may be returned, having it shown in the same tabular format as everything else with a `type` and `description` column would be ideal stylistically

**Comment by tgreyuk** [comment]
Hi - thanks for this.

> Functions should be able to be parsed into a list similar to how properties are for stylistic consistency

I'm not too sure how this would work in practice. Incidentally typedoc does not recognize the "@function" tag and attaches no particular meaning to it and will even throw a warning is 0.26.

It doesn't quite address your question, but you could simply write a markdown table in the comments such as:

```
/*
 * | Function    | Description  |
 * |-------------|-------------------------------------------------------------  |
 * | `fromJson`  | The method used to parse a class from a valid JSON string  |
 * | `toJson`    | The method used to parse a class to a valid JSON string  |
 * | `toObject`  | The method used to parse a class to a generic TypeScript `Object`  |
 * | `validate`  | The method used to parse a class to a generic TypeScript `Object`  |
 * | `clone`     | The method used to clone a class to an identical copy of itself |
 */ 
 ```

> It may be worthwhile to extend this to returns values, as well - while only one item may be returned, having it shown in the same tabular format as everything else with a type and description column would be ideal stylistically.

Again interesting idea but not too sure how it would work in all scenarios. Functions might have many elements including parameters and type parameters including type and description.

**Comment by tgreyuk** [comment]
Closing as per above comments.
