### ISSUE TITLE
vitepress example broken when cloned locally

### ISSUE THREAD

**Issue by bukowa** [typedoc2md/typedoc-plugin-markdown#643]
### What package is the bug related to?

typedoc-vitepress-theme

### Describe the issue

I followed https://github.com/typedoc2md/typedoc-plugin-markdown-examples/tree/main/integrations/vitepress

1. First I had to change dir in `typedoc.json` to properly resolve:
```typedoc.json
  "entryPoints": ["../../dummy-api/src/*"],
````

2. `npm run docs:dev`
3. Visit website and try clicking "Next Page" you will realize you are going back.

### TypeDoc configuration

```json
{
  "entryPoints": ["../../dummy-api/src/*"],
  "plugin": ["typedoc-plugin-markdown", "typedoc-vitepress-theme"],
  "githubPages": false,
  "readme": "none",
  "indexFormat": "table",
  "useCodeBlocks": true,
  "disableSources": true,
  "textContentMappings": {
    "title.indexPage": "API Reference",
    "title.memberPage": "{name}"
  }
}
```

**Comment by tgreyuk** [comment]
Sorry I can't replicate. Next page link is working correctly here? https://typedoc-vitepress-theme-example-docs-rf58bio35.vercel.app/api/

**Comment by bukowa** [comment]
> Sorry I can't replicate. Next page link is working correctly here? https://typedoc-vitepress-theme-example-docs-rf58bio35.vercel.app/api/

Team Access Required

**Comment by bukowa** [comment]
Tried on second PC and 4 browsers with fresh project. When you navigate "Next Page" several times you will realize it's broken as you go back to the root `Api`.

**Comment by tgreyuk** [comment]
Ok should be fixed now in typedoc-vitepress-theme@1.01 (there was some bad paths in sidebar file).

**Comment by bukowa** [comment]
Thanks ill check this later

**Comment by bukowa** [comment]
Working on my end with new example ^^
