### ISSUE TITLE
githubPages option does not generate .nojekyll file

### ISSUE THREAD

**Issue by scottschreckengaust** [typedoc2md/typedoc-plugin-markdown#650]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

The documentation for `typedoc` states, https://typedoc.org/options/output/#githubpages:

> --githubPages Generate a .nojekyll file to prevent 404 errors in GitHub Pages. Defaults to `true`

There is no `.nojekyll` file generated, and if there is a `.nojekyll` file, it is deleted.

```bash
touch docs/.nojekyll
typedoc --plugin typedoc-plugin-markdown
```

_FYI: I opened an issue in `typedoc`, https://github.com/TypeStrong/typedoc/issues/2635, and it was mentioned that the plugin may be overriding_

### TypeDoc configuration

- typedoc-plugin-markdown@4.1.2
- typedoc@0.26.3
- typescript@5.5.3
- Node.js version: 20.9.0
- OS: macOS Sonoma 14.5 M2

### Expected behavior

Expecting a `.nojekyll` file in the destination output folder.

**Comment by scottschreckengaust** [comment]
Well, I guess I needed to fully read the documentation...https://typedoc-plugin-markdown.org/docs/typedoc-usage

**Comment by tgreyuk** [comment]
This seems like a reasonable request - if there is a use-case for this id be happy to implement.
