### ISSUE TITLE
flattenOutputFiles is true, but the name structure should be text-text-text-text.md

### ISSUE THREAD

**Issue by Xtravaganz** [typedoc2md/typedoc-plugin-markdown#654]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

# Current state
![grafik](https://github.com/user-attachments/assets/b4562d10-4836-434d-9aa4-b9c74de4ecdc)

# Desired state
![grafik](https://github.com/user-attachments/assets/4c53455d-2eb0-42ea-b17e-a2ecd16cee63)

Is it possible to get an option for this in the config?

It would be very cumbersome to parse every Markdown and set the link structure so that the files can be found accordingly

Since we use relative paths in the web page structure this would be a great help, I would like to avoid this unnecessary README.md creation in the extended folder creation that comes up in the `flattenOutputFiles false`.

Or perhaps I have overlooked the option in the documentation to separate the names with `-` instead of `.`, in which case I would appreciate a tip.

**Comment by tgreyuk** [comment]
Hi @Xtravaganz,

I understand the request to configure the filename convention.

Could you please clarify this point?

> Since we use relative paths in the web page structure this would be a great help, I would like to avoid this unnecessary README.md creation in the extended folder creation that comes up in the flattenOutputFiles false.

**Comment by Xtravaganz** [comment]
> Hi @Xtravaganz,
> 
> I understand the request to configure the filename convention.
> 
> Could you please clarify this point?
> 
> > Since we use relative paths in the web page structure this would be a great help, I would like to avoid this unnecessary README.md creation in the extended folder creation that comes up in the flattenOutputFiles false.

Of course:
![grafik](https://github.com/user-attachments/assets/0085dbcc-0efa-4e67-8d6f-59ab846c7905)
I prefer directly the jump to MainController without the README.md jump.

![grafik](https://github.com/user-attachments/assets/34f0336e-4a6f-458d-a20a-99793d04753b)
![grafik](https://github.com/user-attachments/assets/0b1bc3ad-28ca-4c94-84dd-5e2feaace2b2)

**Comment by tgreyuk** [comment]
Urls can be parsed with custom plugin. Example here https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/tree/main/issues/654/docs
