### ISSUE TITLE
Examples block not being rendered

### ISSUE THREAD

**Issue by charlesLoder** [typedoc2md/typedoc-plugin-markdown#656]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

First, thanks for this great tool!

Under some circumstances, `@examples` aren't rendered in Markdown. In particular, I have a function from my library where the examples aren't rendered in markdown, even though the TSDoc comments are valid and parsed correctly by Typedoc.

## Reproducible example

See a reproducible example [here](https://stackblitz.com/edit/vitejs-vite-7k4pv8?file=package.json), and run `npm run docs`.

In `src/add.ts` you'll see a sanity check. There are two functions with similarly structured docs. This one works fine.
The `add()` function is just some regular docs, and `addWithNonWorkingExamples()` function has the docs for my function that does not work. This just demonstrates that the doc comments are correct 

In `my_func_with_examples.✅.ts`, you'll see my function. Note that the only way to get the examples to render was by removing the `@param` and `@returns` comments. The examples are rendered but only by modifying the comments.

In `my_func_no_examples.⛔️.ts`, you'll see my function that is not working correctly. The only difference between this function and the one above (besides the name) was the removal of the `@param` and `@returns` comments, and there is no difference in the docs between this function and `addWithNonWorkingExamples()` from `add.ts`.

When you run the docs command, the Typdoc JSON output is in `functions.json`. The example blocks are there in the JSON, but in the function that does not work, the only noticeable difference is the lack of:

```json
{
  "kind": "text",
  "text": "\n\n"
},
```

as the first text node of the second example comment.

### TypeDoc configuration

`package.json`:

```json
{
  "name": "typescript-markdown-example",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "docs": "rm -rf docs && typedoc --json ./docs/functions.json"
  },
  "devDependencies": {
    "typedoc": "^0.26.4",
    "typedoc-plugin-markdown": "^4.2.1",
    "typescript": "^5.2.2",
    "vite": "^5.3.4"
  }
}
```

`typedoc.json`

```json
{
  "plugin": ["typedoc-plugin-markdown"],
  "out": "./docs",
  "entryPoints": ["src/index.ts"]
}
```

### Expected behavior

I would expect to see the example rendered in Markdown

**Comment by tgreyuk** [comment]
Thank you for the detailed description and example - much appreciated :).

This behaviour should now be fixed in typedoc-plugin-markdown@4.2.2

**Comment by andreascorti** [comment]
Hello @tgreyuk, thanks for your work. Since last update, the behavior on comments has changed, but now it seems the `@returns` is not anymore in the generated MD and json.

You check check this [https://stackblitz.com/edit/example-f74xu4returns?file=generated%2Fmd%2Ffunctions%2FcreateConfig.md
](stackblitz). 
If you run `npx typedoc` with the markdown plugin, `@returns` text of the `createConfig` won't be neither in the json nor in the md generated.
If you remove the markdown plugin from the config, then the `@returns` text will be in the returns tag in the createConfig signature.

Could you kindly have a look?

**Comment by tgreyuk** [comment]
@andreascorti thanks for raising this (and providing example). Please try typedoc-plugin-markdown@4.2.3.

**Comment by allista** [comment]
I confirm it works now.
Thank you for the quick fix!
