### ISSUE TITLE
htmlTable is missing thead and tbody

### ISSUE THREAD

**Issue by xixixao** [typedoc2md/typedoc-plugin-markdown#671]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

When I use htmlTable format for `parametersFormat` option, the generated tables don't have `thead` and `tbody` tags. React SSR (like Nextra's), chokes on such tables.

### TypeDoc configuration

latest

### Expected behavior

Correctly use `thead` and `tbody` to allow using the generated code as tables in MDX.

**Comment by tgreyuk** [comment]
Fix in typedoc-plugin-markdown@4.2.5
