### ISSUE TITLE
[Docs website]: `[sidebar guide](/plugins/docusaurus/guide/sidebar)` lead to the /404

### ISSUE THREAD

**Issue by dmytro587** [typedoc2md/typedoc-plugin-markdown#684]
### What package is the bug related to?

docusaurus-plugin-typedoc

### Describe the issue

The `[sidebar guide](/plugins/docusaurus/guide/sidebar)` links that meets on the docs site leads to the /404 pages.

<details><summary>Video example</summary>
<p>

https://github.com/user-attachments/assets/2fb36b4f-5ff6-4e11-ac11-254c0238e4f0

</p>
</details> 

Invalid links:
https://github.com/typedoc2md/typedoc-plugin-markdown/blob/c0744f07abfb5de31d10e182df9f5be3497a9196/packages/docusaurus-plugin-typedoc/src/options/declarations.ts#L13

https://github.com/typedoc2md/typedoc-plugin-markdown/blob/c0744f07abfb5de31d10e182df9f5be3497a9196/devguide/docusaurus-plugin-typedoc/options/namespaces/declarations/README.md?plain=1#L17

https://github.com/typedoc2md/typedoc-plugin-markdown/blob/c0744f07abfb5de31d10e182df9f5be3497a9196/docs/pages/plugins/docusaurus/options.mdx?plain=1#L41

### Expected behavior

Not sure, but I believe these links should go to `/plugins/docusaurus/sidebar`.

**Comment by tgreyuk** [comment]
Thanks - updated.
