### ISSUE TITLE
Support `@group` with `@module` as main navigation

### ISSUE THREAD

**Issue by gossi** [typedoc2md/typedoc-plugin-markdown#685]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

I'm using typedoc to document my domain. Therefore I changed the toplevel navigation to sound less techie and more friendly to non-tech people. Here is the relevant code:

```ts
/**
 * @group Domain Objects
 * @module Ride
 */

// in the index.ts file
```

along with `@category` to give meaning to my code. Here's the typedoc configuration:

```ts
  "navigation": {
    "includeCategories": true,
    "includeGroups": true,
    "includeFolders": false
  },
  "categorizeByGroup": false,
```

that gives me that navigation in typedoc:

<img width="219" alt="Bildschirmfoto 2024-09-04 um 16 51 45" src="https://github.com/user-attachments/assets/bbf8c8e1-83ef-4569-a4aa-7a6b49cc2c51">

When using `typedoc-plugin-markdown` (and `typedoc-vitepress-theme` for display) this setting is not respected, here is the result:

<img width="222" alt="Bildschirmfoto 2024-09-04 um 16 52 38" src="https://github.com/user-attachments/assets/25e3d8ba-2f05-461b-aecd-e337c28f25c2">

## Repro

I have a repro repo with the example above: https://github.com/gossi/rideshare/tree/go-nest/core

This is part of a monorepo, it is the linked package above. You can safely ignore all other packages in there:

1. checkout
2. `pnpm install`
3. `cd core`
4. `pnpm doc`
5. `pnpm docs:dev`

You can also comment out `typedoc` plugin usage in `typedoc.json` to see the result from typedoc itself.

### Proposed solution

The navigation structure generated into `typedoc-sidebar.json` will include that and `typedoc-vitepress-theme` will use it to render the navigation tree as configured.

**Comment by tgreyuk** [comment]
Please try typedoc-plugin-markdown@4.2.7

<img width="585" alt="Screenshot 2024-09-05 at 22 26 14" src="https://github.com/user-attachments/assets/9c468f2b-15fa-49dc-b575-49f475a82ecc">

**Comment by gossi** [comment]
That's fantastic. Great job. Thank you very much 😊
