### ISSUE TITLE
Reflections with `@internal` are still included in docs when `excludeInternal=true`

### ISSUE THREAD

**Issue by dielsalder** [typedoc2md/typedoc-plugin-markdown#687]
### What package is the bug related to?

docusaurus-plugin-typedoc

### Describe the issue

I want to be able to set `excludeInternal: true` in typedoc options to exclude members with `@internal` keyword. According to https://typedoc-plugin-markdown.org/docs/typedoc-usage, this should be possible.

Currently, markdown docs are still generated for the reflections with the @internal tag. 
Source code
``` typescript
/**
 * Get the status of a list of POIs
 * @internal
 */
export async function getBulkPoiStatus({
```

MD docs (getBulkPoiStatus.md)
``` md
# getBulkPoiStatus()

> **getBulkPoiStatus**(`__namedParameters`): `Promise`\<[`PoiStatus`](../../types/type-aliases/PoiStatus.md)[]\>

**`Internal`**
```

### TypeDoc configuration

Typedoc version: 0.26.0
docusaurus-plugin-typedoc version: 1.0.5

Config file (docusaurus.config.js):
```
  plugins: [
    [
      'docusaurus-plugin-typedoc',

      // Plugin / TypeDoc options
      {
        entryPoints: [
          '../libs/packageName/',
          '../libs/types/',
          '../libs/helpers/'
        ],
        tsconfig: '../tsconfig.docs.json',
        entryPointStrategy: "packages",
        sidebar: {
          autoConfiguration: true,
          position: 1,
          indexLabel: 'API Reference',
        },
        cleanOutputDir: true,
        expandObjects: true,
        excludeScopesInPaths: true,
        readme: "../README.md",
        mergeReadme: true,
        typeDeclarationFormat: "htmlTable",
        textContentMappings: {
          "title.memberPage": "{name}",
        },
        excludeInternal: true
      },

    ],
  ],
```

### Expected behavior
Markdown files should not be generated for reflections with `@internal`

_No response_

**Comment by tgreyuk** [comment]
Ah ok.  I believe there is a `packageOptions` option you can use in your root `typedoc.json`, but I can't find any docs for it apart from in the changelog https://typedoc.org/guides/changelog/#features-5.

```
"packageOptions": { "excludeInternal:true": "main" }
```
