### ISSUE TITLE
How to enable source code highlight in docusaurus?

### ISSUE THREAD

**Issue by aoki-h-jp** [typedoc2md/typedoc-plugin-markdown#691]
### What package is your question related to?

docusaurus-plugin-typedoc

### What would you like to ask?

hi, I'm aoki.

I use your `docusaurus-plugin-typedoc`. I want to show source code highlight in docusaurus.
So, I implemented like this used also `typedoc-plugin-inline-sources`.

```
/**
 * GET /api/XXXX
 * `ja` example `en` example
 * @param formData `ja` example `en` example
 * @returns `ja` APIの応答 `en` API response
 * @source
 */
```

However, the source code highlight does not appear on docusaurus, only the title of the Source section.
Is there any way to achieve Source code highlight by using only `docusaurus-plugin-typedoc`?
I would like to know if there is such a way. If not, please consider adding such a feature.

**Comment by tgreyuk** [comment]
I have just tested and it does work. Can i please confirm that you have added the plugin to options config ?- i.e:

`docusaurus.config`:

```
plugins: [
    [
      "docusaurus-plugin-typedoc",
      {
        plugin: ["typedoc-plugin-inline-sources"],]
```

**Comment by aoki-h-jp** [comment]
@tgreyuk 
Thank you for quick response.
I just implement like this, it works!

```
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: ['./my-external-repo/frontend/src/**/*.ts', './my-external-repo/frontend/src/**/*.tsx'],
        tsconfig: './my-external-repo/frontend/tsconfig.json',
        plugin: ["typedoc-plugin-inline-sources"]
      },
    ],
```

It seemed that I had just not set up the config file correctly.
I apologize for waste your time.
