### ISSUE TITLE
docs bug with "entryFileName"

### ISSUE THREAD

**Issue by Zamiell** [typedoc2md/typedoc-plugin-markdown#692]
### What package is your question related to?

typedoc-plugin-markdown

### What would you like to ask?

On this page:
https://typedoc-plugin-markdown.org/plugins/docusaurus/options

It says that it uses `"entryFileName": "index.md"`.

However, "entryFileName" is not documented on the list of options:
https://typedoc-plugin-markdown.org/plugins/docusaurus/options

It is also not a TypeDoc option:
https://typedoc.org/options/

Is this a bug in the docs?

**Comment by tgreyuk** [comment]
This is a typedoc-plugin-markdown option https://typedoc-plugin-markdown.org/docs/options/file-options#--entryfilename.

Sorry it probably is a bit confusing having options documented in separate places. There is a link to these options at the top of the options page but it should probably be made more explicit.

![Screenshot 2024-09-27 at 13 36 46](https://github.com/user-attachments/assets/082817e8-aa0c-4a7e-93c0-a90c30abe604)

**Comment by Zamiell** [comment]
Oh sorry, I missed that. Thank you for the quick reply!

**Comment by tgreyuk** [comment]
I will review the docs and try to make clearer. This is all useful feedback.
