### ISSUE TITLE
Bug: `@returns` tag missing in generated markdown

### ISSUE THREAD

**Issue by m1rn** [typedoc2md/typedoc-plugin-markdown#694]
### What package is the bug related to?

typedoc-plugin-markdown

### Description:
When using `typedoc` with the `typedoc-plugin-markdown` extension, the generated markdown content omits the `@returns` tag from the documentation comments. This results in incomplete documentation, as the `@returns` information is crucial for understanding the return value of functions and types.

### Expected Behavior:
The markdown documentation should include the content from the `@returns` tag, as it does when generating HTML using the base `typedoc` setup. The `@returns` description should be visible under each type that has it documented.

### Actual Behavior:
The `@returns` tag and its description are missing entirely from the generated markdown output.

### Steps to Reproduce:
1. Set up a TypeScript project with `typedoc` and `typedoc-plugin-markdown`.
2. Include a type with a `@returns` tag in the doc comments.
3. Run the `typedoc` command to generate markdown documentation.
4. Check the generated markdown for the missing `@returns` section.

You can view the minimum reproducible example here:  
[Reproduction URL](https://stackblitz.com/edit/stackblitz-starters-3jln6g?file=package.json)

### Environment:
- `typedoc` version: `0.26.7`
- `typedoc-plugin-markdown` version: `4.2.8`
- TypeScript version: `5.5.4`
- Node.js version: `5.5.4`

### Additional Context:
This issue may cause incomplete documentation for users who rely on markdown output for their TypeScript projects. It would be helpful to ensure all relevant tags, including `@returns`, are properly processed in the markdown output.

**Comment by tgreyuk** [comment]
thanks - will go into next release.

**Comment by tgreyuk** [comment]
fix in typedoc-plugin-markdown@4.2.9.
