### ISSUE TITLE
Make object documentation less verbose

### ISSUE THREAD

**Issue by norswap** [typedoc2md/typedoc-plugin-markdown#703]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

I have an exported variable that is a deeply nested `const` object.

Using `"expandObjects": true`, I get a very pleasant code representation of my object in the docs.

However, every property gets listed in a way that is very noisy (every property gets its own title and section, as well as every sub-property, etc etc).

Example: https://happychain.pages.dev/react/api/variables/chains#type-declaration

### Proposed solution

An option that lets us choose between
- the current behaviour
- not rendering documentation (sections) for any property
- only rendering documentation (sections) for properties that have their own docstring

**Comment by tgreyuk** [comment]
Thank you. This does seem like a reasonable suggestion and will have a look at including some kind of configuration around this.

**Comment by tgreyuk** [comment]
@norswap I have been having a look at this. One thing I am exploring is simply replacing the entire "Type declaration" section with the source from the ts compiler exposed by the option `typeDeclarationFormat: "source"`.

In your use-case you would see something like this:

![Screenshot 2024-11-18 at 12 05 15](https://github.com/user-attachments/assets/0a360808-32db-443c-ae32-013082434dfd)

Would you find this kind of solution satisfactory?

**Comment by norswap** [comment]
Yes, that seems perfect :)

**Comment by tgreyuk** [comment]
ok went for a slightly different approach in the end. 

`typedoc-plugin-markdown@4.3` exposes an additional property "typeDeclarationVisibility" that can be set to "compact" which hopefully improves things in your use case, but let me know. Docs here https://www.typedoc-plugin-markdown.org/docs/options/display-options#--typedeclarationvisibility
