### ISSUE TITLE
globals.md / packages.md vs index.md

### ISSUE THREAD

**Issue by wighawag** [typedoc2md/typedoc-plugin-markdown#708]
### What package is your question related to?

typedoc-plugin-markdown

### What would you like to ask?

I am using typedoc-plugin-markdown along with typedoc-vitepress-theme and I noticed that typedoc-plugin-markdown generate globals.md file for my modules and a packages.md 

These looks like index file to me, but the plugin also generate index.md file and these is the one referenced in the generated `typedoc-sidebar.json` by typedoc-vitepress-theme

Is there an option to merge index.md and (globals.md/packages.md) ?

**Comment by tgreyuk** [comment]
You can set `mergeReadme: true` to append the index page to the readme page to create a single entry point file, or `readme:  'none'` to ignore readme file completely.

**Comment by wighawag** [comment]
Thanks @tgreyuk 

`mergeReadme: true` will probably work for what I want. It seems it merge the top level README in if none if present at the package level, so I might just need to create empty README file there if I want to document the module via `@module` tag in index.ts. 

I tried to set` "readme": "none"` in typedoc.json but it does not seem to do anything. I was hoping it would remove the need for me to create these empty README

**Comment by tgreyuk** [comment]
To set readme:none for individual packages in addition to the top level you can try:
```
packageOptions: {
 readme: "none"
}
```

**Comment by Deja-vuuu** [comment]
> To set readme:none for individual packages in addition to the top level you can try:要为顶层包之外的各个包设置 readme:none，您可以尝试：
> 
> ```
> packageOptions: {
>  readme: "none"
> }
> ```

What does this mean? My current requirement is that I don’t want to generate a readme file, how to configure it. None of the following configurations work ~

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/dfa9bdef-35bc-4198-91f9-2ce40f13d311" />
