### ISSUE TITLE
Is there an option to hide type reference links in table mode?

### ISSUE THREAD

**Issue by vasco-cruz** [typedoc2md/typedoc-plugin-markdown#709]
### What package is your question related to?

typedoc-plugin-markdown

### What would you like to ask?

Hello, I'm a newer of Typedoc and Typedoc markdown.

I want to generate the documentation in table mode, but without links in the types, similar to how it appears in list mode. Is there a parameter for this?

List mode:
![image](https://github.com/user-attachments/assets/850558ab-35b8-448a-93b2-5f21cc71ab89)

Table mode:
![image](https://github.com/user-attachments/assets/075c28db-42cb-4c04-899b-dd262eb80c75)

Thanks

**Comment by tgreyuk** [comment]
Currently if a reference type is resolved in the documentation a link will be created to it in a table and this can't currently be configured. The list mode in your example is a bit different as this has been configured with `useCodeBlock` which puts the entire declaration in a code block. 

I am not sure there is a strong use case to introduce a new option to handle this specific behaviour.

**Comment by vasco-cruz** [comment]
Thank you very much for the information.

As a temporary solution, I found this workaround:
find ./typedoc/ -type f -exec sed -i 's/\[\(`.*`\)\](.*)/\1/g' {} \;

After generating the documentation, I remove all the links and leave only the type name.
