### ISSUE TITLE
Would rendering the Returns section as a table look better?

### ISSUE THREAD

**Issue by ilg-ul** [typedoc2md/typedoc-plugin-markdown#712]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

Currently the parameters can be rendered as a table, and I think they look better than the default sequence of lines.

The Returns section is simpler, a type and possibly a description:

![Screenshot 2024-10-31 at 12 54 24](https://github.com/user-attachments/assets/012f2893-390b-4942-9180-d24d5abed8a7)

### Proposed solution

I wonder if rendering it also like a small table, with two columns (Type & Description) would not make it look slightly better.

Something like this:

### Returns 

|  Type | Description |
|  :------ | :------ |
| `boolean` | True if the current log level is equal to the given  level or higher. |

Similarly to `parametersFormat`, a configuration option can be used to control the rendering.

**Comment by tgreyuk** [comment]
Thanks - yes potentially could introduce a new option for this. I will review it.

**Comment by tgreyuk** [comment]
Tables could work well for simple primitive types, but return types might be complex and not suitable for table layout so probably won't be implementing this. Thanks for suggestion though if I come up with a good solution will revisit.
