### ISSUE TITLE
Better rendering for curried functions

### ISSUE THREAD

**Issue by TomerAberbach** [typedoc2md/typedoc-plugin-markdown#714]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

I'm using `typedocs-plugin-markdown` for a library of mine that has many curried functions, and unfortunately it currently generates overly verbose documentation for those functions.

For example, for this function: https://github.com/TomerAberbach/lfi/blob/fd6e1ff9d7b7d249090f89ead6d0a30e26aba2e4/src/operations/predicate.d.ts#L203-L223

I get these docs:
https://github.com/TomerAberbach/lfi/blob/fd6e1ff9d7b7d249090f89ead6d0a30e26aba2e4/docs/functions/includes.md

There are a couple of problems here:
1. There is one documentation comment for all the overloads, but it's rendered multiple times
2. One function is basically a "prefix" of the other so I would expect them to be merged somehow

### Proposed solution

In terms of prior art, based on the screenshot in this comment, https://github.com/TypeStrong/typedoc/issues/1421#issuecomment-751407709, it seems like the regular typedoc is able to handle this case with some sort of overload signature merging? Might be worth looking into what logic typedoc is doing there. I tried to figure it out, but couldn't nail down where it happens.

**Comment by tgreyuk** [comment]
Thank you. Will take a look and try to align with the default theme as much as possible.

**Comment by TomerAberbach** [comment]
Thank you!

**Comment by tgreyuk** [comment]
@TomerAberbach `typedoc-plugin-markdown@4.3.0` now correctly places the comments.

The output now correctly renders a single overall comment block above the overload signatures. Each overload has a "Call Signature" heading which easily divides the signatures when scanning the docs.

Markdown:

<img width="805" alt="Screenshot 2024-11-27 at 20 46 53" src="https://github.com/user-attachments/assets/b3a5bfd4-6e23-4217-903b-a602ab86a301">

HTML:

<img width="751" alt="Screenshot 2024-11-27 at 20 46 29" src="https://github.com/user-attachments/assets/4bfbf6b3-e6c3-454e-a627-72513eeea44b">

Also output example can be seen here https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/blob/main/issues/714/docs/md/functions/includes.md 

Hope this is acceptable but let me know.

**Comment by TomerAberbach** [comment]
It looks great, thank you so much! I just went ahead and published it to my new documentation site:

https://lfi.dev/docs/api/functions/includes

By the way, any reason you're not on GitHub sponsors? `typedoc-plugin-markdown` is amazing and I'd be happy to sponsor :)

**Comment by tgreyuk** [comment]
No problem happy to help and thanks for feedback. I probably should get around to setting up a sponsor page :)
