### ISSUE TITLE
Use {group} in textContentMappings

### ISSUE THREAD

**Issue by Huxpro** [typedoc2md/typedoc-plugin-markdown#715]
### What package is the feature request related to?

typedoc-plugin-markdown

### Background

`@group` is useful to simulate custom member types, e.g. `@group Events`, `@group Components`.

By allowing the use of `{group}`, it will be convenient to title file as `Event: onClick` or `Component: Button()` via `textContentMappings`.

### Proposed solution

Support `{group}` in textContentMappings, or even a callback that does the string interpolation?

Maybe it's better to build a custom theme for this use case?

**Comment by tgreyuk** [comment]
Could do something like this, although {groupMember} would probably more explicit. A callback with context would be very useful as you could do conditional interpolation according to type.

**Comment by tgreyuk** [comment]
In `typedoc-plugin-markdown@4.3.0` you can do the following with a JS config file:

```
 pageTitleTemplates: {
    member: (args) => `${args.group.slice(0, -1)}: ${args.name}`,
  },
```

Example:

https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/blob/main/issues/715/docs/md/functions/Button.md
