### ISSUE TITLE
groupHeading no more respected when hideGroupHeading is true

### ISSUE THREAD

**Issue by Huxpro** [typedoc2md/typedoc-plugin-markdown#716]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

The source code is something like

```
interface ButtonProps;
interface ButtonRef;
export function Button (){..};
export type { ButtonProps, ButtonRef };
```

It was correctly generating `Function` prior to `interfaces`. But when `hideGroupHeadings: true`  is present. The `groupHeading` doesn't seem to be respected.

See the generated catelog:

<img width="276" alt="image" src="https://github.com/user-attachments/assets/0af39126-4857-4e49-9e13-7e0dc73b4f23">

### TypeDoc configuration

```ts
groupOrder: ['Function', 'Interface', '*'],
outputFileStrategy: 'modules',
hideGroupHeadings: true,
```      

### Expected behavior

groupOrder is still respected when `hideGroupHeading` is given true

**Comment by tgreyuk** [comment]
Fix in `typedoc-plugin-markdown@4.3.0`

Example: https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/blob/main/issues/716/docs/md/README.md
