### ISSUE TITLE
How do I determine the order of properties in the documentation?

### ISSUE THREAD

**Issue by shalugin** [typedoc2md/typedoc-plugin-markdown#717]
### What package is your question related to?

docusaurus-plugin-typedoc

### What would you like to ask?

I see that the documentation that generates on Windows is different from that generated on macOS.
Here is an example where the order of properties is different:

<img width="1492" alt="image" src="https://github.com/user-attachments/assets/e9fa9753-0770-4387-90df-511c11c7e3ac">

This output is obtained with the same plugin settings.

**Comment by tgreyuk** [comment]
This is most likely happening on TypeDoc side but its interesting nonetheless. Would you mind comparing the behaviour to the default html theme? What does the source code look like?

**Comment by shalugin** [comment]
It looks like you are right and it is controlled by TypeDoc (https://typedoc.org/options/organization/#sort). I'll play around with their configuration and try to find the right ordering settings. I've tried a few already, but with no luck.

My `typedoc.json`:

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": [
    "./index.ts"
  ],
  "disableSources": true,
  "excludePrivate": true,
  "excludeProtected": false,
  "readme": "none"
}

```

**Comment by tgreyuk** [comment]
Closing as this plugin does not directly control the order props.
