### ISSUE TITLE
Unioned type for function param emits `object` instead of inline type for type that is based on a `typedef`

### ISSUE THREAD

**Issue by techfg** [typedoc2md/typedoc-plugin-markdown#720]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

When a function parameter accepts a union type which contains a type that is based on a `typedef`, the type that was created via `typedef` emits as `object` instead of the inline type.

Repro: https://stackblitz.com/edit/vitejs-vite-gkbey1

**Steps to Reproduce**
1. Open [repro](https://stackblitz.com/edit/vitejs-vite-gkbey1)
2. `npm run docs:md`
3. View files in `docs-md/functions`

**Actual Result**
Generated markdown for function `handleFoo` which accepts the union `Foo | null` contains `object` for the type of `Foo`

```text
• **a**: `null` \| `object`
```

**Additional Information**
1. The issue does not occur when generating html files (`npm run docs:html`)
2. The issue does not occur in the following situations:
    1. `handleFooOnly` - Does not contain a union, param `a` is type `Foo`
    2. `handleFoo2` - Defines a union type `FooExplicit` separately and uses it for the type parameter for `a` instead of the inline union
    3. `handleFooExplicit` - Uses a union type inline but does not use `typedef`

### TypeDoc configuration

typedoc: 0.26.11
typedoc-plugin-markdown: 4.2.10
typescript" 5.6.3

### Expected behavior

The type `Foo` should be generated inline similar to the way `handleFooOnly` which does not have a union type emits.

```
• **a**
• **a.a**: `string` = `''`
• **a.b**: `string` = `''`
```

**Comment by tgreyuk** [comment]
Thanks for detailed description.

Fix in typedoc-plugin-markdown@4.3.0

It was a bit tricky to format this in a decent way but currently is produces this output.

<img width="523" alt="Screenshot 2024-11-27 at 18 36 35" src="https://github.com/user-attachments/assets/d8a491d7-45c7-4a69-b47b-2cef01ac617c">

https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/blob/main/issues/720/docs/md/functions/handleFoo.md

Please note output for parameter listings has changed a bit for readability.

**Comment by techfg** [comment]
Hi @tgreyuk -

Thanks for the quick response on this, grealty appeciated!

Understood that the formatting gets complicated in this scenario, however I think the current in 4.3.0 is missing a key part of the type by not having a `|` between the types.

Repro: https://stackblitz.com/edit/vitejs-vite-8b5crt?file=src%2Findex.ts

TypeDoc configuration
typedoc: 0.27.0
typedoc-plugin-markdown: 4.3.0
typescript" 5.7.2

In the case of [handleFooExplicit](https://stackblitz.com/edit/vitejs-vite-8b5crt?file=src%2Findex.ts%3AL8), the generated result is:
![image](https://github.com/user-attachments/assets/f08a6e10-eacd-4da2-899c-7c890fd8a570)

However, in the case of [handleFoo](https://stackblitz.com/edit/vitejs-vite-8b5crt?file=src%2Findex.ts%3AL6), the generated result is:
![image](https://github.com/user-attachments/assets/861a3c4f-03d6-493f-8771-2a490107892e)

Even thought the types are defined in an identical way with the only difference being their "upstream" definitions:
```ts
export const handleFoo = (a: Foo | null) => {};
export const handleFooExplicit = (a: FooExplicit | null) => {};
```

In the HTML version, the result is:
![image](https://github.com/user-attachments/assets/99f763f9-bf33-421a-9a31-d874cd7e0015)

Do you think it makes more sense and would it be possible to delimit `null` and `{`a`: `string`;`b`: `string`; }` with a `|` and just put on the same line?

**Comment by tgreyuk** [comment]
Yes makes sense. I assume example 1 is preferable to example 2?

Example 1:
<img width="346" alt="Screenshot 2024-11-27 at 22 39 30" src="https://github.com/user-attachments/assets/936af90f-0843-48da-ac20-a9635bdd585d">

Example 2:
<img width="336" alt="Screenshot 2024-11-27 at 22 39 56" src="https://github.com/user-attachments/assets/f10926e5-b173-4b89-af95-4f846614768e">

**Comment by techfg** [comment]
Thanks @tgreyuk.  Yeah, my preference would be Example 1 as it mirrors what the output is in the `FooExplicit` scenario and also the HTML equivalent.

A few additional notes:

1. I realized that the typedoc 0.27.0 repro from my last message wasn't saved so I've updated it to ensure the lastest typedoc, typedoc-plugin-markdown & typescript are referenced in package.json
2. Another scenario where this same formatting issue arises is in the following - I've added [handleFooInline](https://stackblitz.com/edit/vitejs-vite-8b5crt?file=src%2Findex.ts%3AL7) to cover this so that you have a repro
```ts
export const handleFooInline = (a: { a: string; b: string } | null) => {};
```
3. Beyond the `|` formatting, the current output emits `a.a` and `a.b` which differs from the generated HTML for the same function which does not include the additional definition of `a` since it's already inlined.  I'm not sure why the extra definition is emitted so possibly there is a good reason it behaves the way it does.  That said, it does differ from what the HTML equivalent generates and in the case where there are multiple complex types in the union, things could get rather confusing I fear.  For example, the following:
```ts
export const handleFooInlineMulti = (
  a: { a: string; b: string } | { x: string; y: string } | null
) => {};
```

Generates the following MD which has two issues:
1. It does not include `{'x': 'string';'y': 'string'; }` in the definition of `a` itself (yellow highlight)
2. It includes additional definition of each complex type of `a` but since they are already documented for `a` itself this results in duplicates (red highlight):
![image](https://github.com/user-attachments/assets/7c108a89-6936-4e69-bfc3-1464b9b49c50)

While the HTML equivalent generates:
![image](https://github.com/user-attachments/assets/ee820f0f-84f8-4249-859a-bdd58e6429c3)

I believe the `{x: string, y:string`} should be emitted for `a` itself here and possibly the additional definition `a.a`, `a.b`, `a.x` & `a.y` isn't needed in this scenario?

**Comment by tgreyuk** [comment]
@techfg thanks for the comments - this kind of detailed feedback is invaluable and greatly appreciated.

> Another scenario where this same formatting issue arises is in the following - I've added [handleFooInline](https://stackblitz.com/edit/vitejs-vite-8b5crt?file=src%2Findex.ts%3AL7) to cover this so that you have a repro

Will review thank you.

> Beyond the | formatting, the current output emits a.a and a.b which differs from the generated HTML for the same function which does not include the additional definition of a since it's already inlined. 

You are correct, the html theme does not include further inlined declarations unless there are associated doc comments, in which case it does render the detailed declaration.

![Screenshot 2024-11-28 at 13 22 29](https://github.com/user-attachments/assets/9ab08681-f699-4274-8ee1-84bdf8f26bb4)

 This is a pattern i have considered implementing too but i found it more deterministic just retain the same behaviour regardless if comments are present. However on reflection there is obviously a case not to render this extended view if there is nothing useful to show (ie associated comments), and aligning with the html theme in this regard is probably the way to go.

> That said, it does differ from what the HTML equivalent generates and in the case where there are multiple complex types in the union, things could get rather confusing I fear. For example, the following:

Yes i thought about this too which is partly why the initial implementation was in blocks, however i think it can be implemented in a way that works, and if we are not displaying inline details all the time it becomes less of an issue.

**Comment by techfg** [comment]
Happy to try to help @tgreyuk, glad your finding the feedback useful :)

Makes sense about where you initially took the approach to always emit vs. only when comments are present.  I do think that trying to mirror the HTML equivalent as much as possible may be the best course but understood if that presents challenges and I don't think it's worth bending over backwards to try to make that happen if its not straightforward enough.  

Just want to make sure you saw the comment about the issue where in the following, `{ x: string; y: string }` is not emitted for `a` (yellow highlighted area):
```ts
export const handleFooInlineMulti = (
  a: { a: string; b: string } | { x: string; y: string } | null
) => {};
```

Thank you!

**Comment by tgreyuk** [comment]
As discussed - fixes in typedoc-plugin-markdown@4.3.1

<img width="387" alt="Screenshot 2024-12-01 at 23 09 40" src="https://github.com/user-attachments/assets/d10bcc92-453e-4c24-bb43-8d9ad9731103">


<img width="541" alt="Screenshot 2024-12-01 at 23 09 53" src="https://github.com/user-attachments/assets/4091e4ed-0a91-4487-a57a-fff04c40469f">

**Comment by techfg** [comment]
Looking good in 4.3.1, thank you @tgreyuk!

Only feedback I'd offer is that there is a `space` between certain areas (green arrows) and `no space` between other areas (red arrows).  For consistency, possibly add a `space` where the red arrows are?

![image](https://github.com/user-attachments/assets/c90ef970-b57d-4c64-a2c7-f896d9d80191)

**Comment by tgreyuk** [comment]
spacing updated in `typedoc-plugin-markdown@4.3.2`

**Comment by techfg** [comment]
Looks great, thanks for the quick response @tgreyuk!
