### ISSUE TITLE
typedoc 0.27.x using ESM

### ISSUE THREAD

**Issue by axel7083** [typedoc2md/typedoc-plugin-markdown#721]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

When upgrading to typedoc 0.27.x the packages in this repositories cannot be used (from my understanding)

**Comment by tgreyuk** [comment]
Thanks - there will be a new release very shortly to support ESM.

**Comment by OlivierZal** [comment]
@tgreyuk, as far as I see it's rather related to peer dependencies version in the package, because it seems to work when forcing `npm i` and building the docs.

However `typedoc@0.27.x` has breaking changes you probably might want to handle in your plugin.

**Comment by tgreyuk** [comment]
Thanks @OlivierZal yep need to convert plugin to ESM. On its way (just some final tests)...

**Comment by axel7083** [comment]
Thanks you @tgreyuk for your reactivity and the update :+1: , kudo :rocket:
