### ISSUE TITLE
[typedoc-vitepress-theme]: Anchors generated by typdoc will not be compatible with vitepress if they contain colon

### ISSUE THREAD

**Issue by aiktb** [typedoc2md/typedoc-plugin-markdown#725]
### What package is the bug related to?

typedoc-vitepress-theme

### Describe the issue

For example, I have an object property named "build:before", the anchor generated by typedoc is "buildbefore", but the anchor generated by vitepress is "build-before".

### More Information
https://github.com/typedoc2md/typedoc-plugin-markdown/blob/834b8100b76b331506d20b86b84dd1fd3afcb90c/packages/typedoc-vitepress-theme/src/index.ts#L78-L85

I noticed that the above implementation is wrong. Line 82 eliminates all non-alphanumeric and "-" characters, which is inconsistent with the implementation of VitePress.

https://github.com/vuejs/vitepress/blob/452d6c77a6afa43faa245452e7d0b360e55a36fb/src/node/markdown/markdown.ts#L16

I found the anchor generation code used by vitepress, we can reuse it.

https://github.com/mdit-vue/mdit-vue/blob/e0c38a4a7d0565a2c4c59dcfbb7e58aa38dc12e3/packages/shared/src/slugify.ts#L1-L25

### TypeDoc configuration

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPointStrategy": "packages",
  "entryPoints": ["../packages/wxt"],
  "plugin": [
    "typedoc-plugin-markdown",
    "typedoc-vitepress-theme",
    "typedoc-plugin-frontmatter"
  ],
  "out": "./api/reference",
  "githubPages": false,
  "excludePrivate": true,
  "excludeProtected": true,
  "excludeInternal": true,
  "readme": "none",
  "frontmatterGlobals": {
    "editLink": false
  }
}

```

### Expected behavior

typedoc generates "build-before" anchor.

**Comment by aiktb** [comment]
If typedoc2md members thinks my understanding is correct, I can open a PR for this. 😊

**Comment by tgreyuk** [comment]
Yes this sounds good. Feel free to open a PR - but if not will get it fixed shortly.

**Comment by aiktb** [comment]
> Yes this sounds good. Feel free to open a PR - but if not will get it fixed shortly.

Hi, I found that the anchors in the table of contents generated by `typedoc-plugin-markdown` have already removed the colon, so this bug is not caused by `typedoc-vitepress-theme`.
I didn't find the reason.

**Comment by tgreyuk** [comment]
I have updated the anchors to be same as vitepress so it might fix your issue. typedoc-vitepress-theme@1.1.1

**Comment by aiktb** [comment]
> I have updated the anchors to be same as vitepress so it might fix your issue. typedoc-vitepress-theme@1.1.1

Thanks for your reply and work.

I have tried this and it didn't solve the problem.

I am sure that the colon in the anchor is eliminated before it is processed by `typedoc-vitepress-theme`, I tried to look for the logic in `typedoc-plugin-markdown` that handles anchors, but I can't understand it.

**Comment by tgreyuk** [comment]
ok thanks for checking. Do you have a reproduction on a public repo so i can investigate properly? Anchors can be created in various places and it is hard to figure out the issue without something to test against.

**Comment by tgreyuk** [comment]
Otherwise a screenshot identifying which link is broken would help a lot.

**Comment by aiktb** [comment]
> Otherwise a screenshot identifying which link is broken would help a lot.

I encountered a little difficulty. I was upgrading all dependencies related to typedoc, and what was actually broken was the ToC anchor in the markdown file.
When I upgraded the dependencies to the latest, the ToC disappeared, so I am still investigating why the ToC disappeared.

This issue can be reproduced at https://github.com/wxt-dev/wxt (I upgraded the latest "typedoc-vitepress-theme" locally, and there was no change remotely)
The broken link is at https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html
![image](https://github.com/user-attachments/assets/472b80b8-5104-42a6-95ed-8c6e2326ccce)

Do you have any idea about the disappearance of the ToC? If I restored the ToC I could create a minimal copy.

**Comment by aiktb** [comment]
Okay, I saw that 4.0.0 breaking changes introduced changes to typedoc-plugin-remark, and I'll create a minimal copy.

**Comment by aiktb** [comment]
Close this. ToC generation after 4.0.0 is no longer related to typedoc-vitepress-theme

Thank you!
