### ISSUE TITLE
Export `PluginOptions` from `typedoc-plugin-frontmatter`

### ISSUE THREAD

**Issue by lukekarrys** [typedoc2md/typedoc-plugin-markdown#737]
### What package is the bug related to?

typedoc-plugin-frontmatter

### Describe the issue

In v1.1.0 `exports` were added to `package.json` which means the `PluginOptions` can no longer be imported from `typedoc-plugin-frontmatter`.

Previously I was doing the (ill advised) `import('typedoc-plugin-frontmatter/dist/options/option-types').PluginOptions` to get the types for the options.

It would be nice if this functionality could be added back by either:
- Adding `types/index` to the package.json exports
- Exporting a public API from the default export (similar to what `typedoc-plugin-markdown` is doing)

### Expected behavior

I would like to be able to access the types for the PluginOptions by doing:

```ts
import('typedoc-plugin-frontmatter').PluginOptions
// or
import('typedoc-plugin-frontmatter/types').PluginOptions
```

**Comment by lukekarrys** [comment]
I ran into the same issue with the recent version of `typedoc-plugin-remark`. I can file a separate issue for that if necessary, but it would be nice if that plugin could be updated in the same way.

**Comment by tgreyuk** [comment]
Hey @lukekarrys,

Sure have exposed as follows:

```
import('typedoc-plugin-frontmatter').PluginOptions
import('typedoc-plugin-remark').PluginOptions
```

Available in:
- `typedoc-plugin-frontmatter@1.1.2`
- `typedoc-plugin-remark@1.2.1`
